apibara/typescript-sdk

.changeset/sour-colts-thank.md, packages/protocol/src/client.ts
Insecure connections cannot be composed. Change the API so that if the
user passes grpc credentials, then they're used as-is.
=> protocol: allow connecting to insecure endpoint

packages/indexer/package.json, packages/indexer/src/index.ts, packages/indexer/src/sinks/index.ts
Export all sinks as separate modules to avoid users importing peer dependencies
even when not used.
=> indexer: export sinks as separate modules

biome.json, examples/evm-client/src/main.ts, examples/indexer/src/indexer.ts, packages/evm/src/filter.test.ts, packages/indexer/package.json, packages/indexer/src/hooks/index.ts, packages/indexer/src/hooks/useKVStore.ts, packages/indexer/src/indexer.ts, packages/indexer/src/plugins/config.ts, packages/indexer/src/plugins/index.ts, packages/indexer/src/plugins/kv.test.ts, packages/indexer/src/plugins/kv.ts, pnpm-lock.yaml
add `kv` plugin, `useKVStore` hook and `KVStore` test. also update `biome` config to check for unused imports
=> indexer: add kv plugin

packages/indexer/package.json, packages/indexer/src/indexer.ts, packages/indexer/src/sink.ts, packages/indexer/src/sinks/csv.ts, packages/indexer/src/sinks/sqlite.ts, packages/indexer/src/testing/vcr.ts, pnpm-lock.yaml
Previously, the `Sink` interface used eventemitter to signal when data was written or flushed.
EventEmitter emits events in order, but doesn't ensure that the listeners are completely done
before calling the listeners for the next events.
This caused issues because we expect listeners for a batch of data to be completely done
before we call the listeners for the next batch of data.
Switch Sink to extend the `Hookable` class so that calls to `callHook` await for all
callbacks to be finished before returning.
=> indexer: make sink hookable to ensure ordering

examples/beaconchain-client/src/main.ts, examples/evm-client/src/main.ts, examples/starknet-client/src/main.ts, packages/beaconchain/src/block.ts, packages/beaconchain/src/filter.ts, packages/beaconchain/src/index.ts, packages/evm/src/block.ts, packages/evm/src/filter.test.ts, packages/evm/src/filter.ts, packages/evm/src/index.ts, packages/indexer/src/indexer.test.ts, packages/indexer/src/indexer.ts, packages/indexer/src/plugins/persistence.test.ts, packages/indexer/src/testing/helper.ts, packages/indexer/src/testing/indexer.ts, packages/protocol/proto/testing.proto, packages/protocol/src/client.ts, packages/protocol/src/config.ts, packages/protocol/src/proto/testing.ts, packages/protocol/src/stream.test-d.ts, packages/protocol/src/stream.test.ts, packages/protocol/src/stream.ts, packages/protocol/src/testing/client.test.ts, packages/protocol/src/testing/mock.test.ts, packages/protocol/src/testing/mock.ts, packages/starknet/src/block.ts, packages/starknet/src/filter.test.ts, packages/starknet/src/filter.ts, packages/starknet/src/index.ts
The DNA protocol sends an empty block to signal to the client that it scanned a
block but didn't find any data.
This happens when the client sends multiple filters in one request.
This PR changes the stream definitions to:
* Require that the schema returns a nullable type.
* Propagate changes to all the types across packages.
We also extend `StreamConfig` to include a `mergeFilter` function that can be
used to merge multiple filters into one.
=> protocol: parse empty block data as null

examples/indexer/package.json, examples/indexer/src/indexer.ts, examples/starknet-indexer/package.json, examples/starknet-indexer/src/indexer.ts, examples/starknet-indexer/src/main.ts, packages/cli/playground/indexers/starknet.indexer.ts, packages/indexer/package.json, packages/indexer/src/context.ts, packages/indexer/src/hooks/index.ts, packages/indexer/src/hooks/useSink.ts, packages/indexer/src/index.ts, packages/indexer/src/indexer.test.ts, packages/indexer/src/indexer.ts, packages/indexer/src/plugins/config.ts, packages/indexer/src/plugins/kv.ts, packages/indexer/src/plugins/persistence.test.ts, packages/indexer/src/plugins/persistence.ts, packages/indexer/src/sink.ts, packages/indexer/src/sinks/csv.test.ts, packages/indexer/src/sinks/csv.ts, packages/indexer/src/sinks/drizzle.ts, packages/indexer/src/sinks/sqlite.test.ts, packages/indexer/src/sinks/sqlite.ts, packages/indexer/src/testing/indexer.ts, packages/indexer/src/testing/setup.ts, packages/indexer/src/testing/vcr.ts, packages/indexer/src/vcr/record.ts, packages/indexer/src/vcr/replay.ts, pnpm-lock.yaml
- upgrade sink interface
- add sink and its transaction to indexer context
- add drizzle sink for postgres
- update csv, sqlite sink
- add `useSink` hook
- update indexer examples
- update persistence and kv plugin
- update vcr and tests
=> indexer: sink rfc

change/@apibara-indexer-eae11f64-2203-4964-a273-9c1536b8fcdd.json, examples/indexer/package.json, examples/starknet-indexer/package.json, package.json, packages/indexer/package.json, packages/indexer/src/sinks/drizzle/insert.ts, packages/indexer/src/sinks/drizzle/utils.ts, pnpm-lock.yaml
Update to the latest drizzle version to solve type issues on new projects.
=> indexer: update drizzle and drizzle sink

change/@apibara-indexer-43e28d2b-5062-4907-8504-f0287b439697.json, examples/starknet-indexer/src/indexer.ts, packages/indexer/src/sinks/drizzle/drizzle.test.ts, packages/indexer/src/sinks/drizzle/utils.ts
This enables developers to use plain pgTable and pgIndexerTable in the same schema file.
=> indexer: rename pgTable to pgIndexerTable

change/@apibara-indexer-67090bf0-932b-45a7-b9a7-91d1ef752364.json, examples/cli/indexers/evm.indexer.ts, examples/cli/package.json, packages/indexer/src/indexer.ts, packages/indexer/src/sink.ts, packages/indexer/src/sinks/csv.ts, packages/indexer/src/sinks/drizzle/drizzle.ts, packages/indexer/src/sinks/sqlite.ts, packages/indexer/src/testing/vcr.ts, pnpm-lock.yaml
Now the indexer can consume a stream that handles reorgs.
=> indexer: add hooks for each message type

change/@apibara-indexer-95c6848e-72aa-429f-bbe9-556a867c123e.json, change/apibara-45ec1e62-bbea-48bc-ac29-b6ea1acc4024.json, examples/cli/indexers/1-evm.indexer.ts, examples/cli/indexers/2-starknet.indexer.ts, packages/cli/src/runtime/internal/app.ts, packages/indexer/build.config.ts, packages/indexer/package.json, packages/indexer/src/plugins/logger.ts
Add a new logger plugin to standardize how users can log information.
This is a simple wrapper around consola for now and will be used later
to make the logger configurable by the user in `apibara.config.ts`.
=> Add logger plugin

.gitignore, change/apibara-5146fc27-9558-48ae-819b-7000820431b8.json, examples/cli/indexers/2-starknet.indexer.ts, examples/cli/indexers/3-starknet-factory.indexer.ts, packages/cli/src/rollup/config.ts
- add `@electric-sql/pglite` as external dependency in rollup for cli
- add pglite persistence in example
- add factory mode example
=> example: add factory mode and pglite persistence

examples/cli/apibara.config.ts, examples/cli/indexers/1-evm.indexer.ts, examples/cli/indexers/2-starknet.indexer.ts, examples/cli/indexers/3-starknet-factory.indexer.ts, examples/cli/lib/db.ts, examples/cli/lib/schema.ts, examples/cli/package.json, examples/cli/test/ethereum.test.ts, examples/cli/test/helper.ts, examples/cli/test/starknet.test.ts, examples/cli/tsconfig.json, examples/cli/vitest.config.ts, pnpm-lock.yaml
updates the cli example to showcase how to use rollup plugins in `apibara.config.ts` under scenarios where you have custom path alias in tsconfig.
=> examples: add ts path alias and rollup typescript plugin

change/@apibara-evm-f1bb6555-a641-4402-82e4-692be980ad21.json, change/@apibara-starknet-5f888e7b-83d2-4a42-b2b5-d60e55fc7d2d.json, packages/evm/proto/data.proto, packages/evm/src/block.ts, packages/evm/src/proto/data.ts, packages/starknet/proto/data.proto, packages/starknet/src/block.ts, packages/starknet/src/proto/data.ts
This PR adds the `{event,message,log}IndexInTransaction` fields to track the index inside a transaction.
=> Update protocol with index in transaction fields

change/@apibara-indexer-00f20a26-f27d-40f3-a4f5-9ae56b471507.json, examples/cli/indexers/1-evm.indexer.ts, examples/cli/indexers/2-starknet.indexer.ts, examples/cli/indexers/3-starknet-factory.indexer.ts, packages/indexer/src/indexer.ts
This is a shortcut for the most common case (specifying only the starting block without the hash).
=> Add startingBlock option

change/@apibara-indexer-10c147e4-d02c-49b5-825f-40ebd5ba16ec.json, change/@apibara-plugin-drizzle-1364b96a-b614-40a0-990f-5844e1845e86.json, change/@apibara-plugin-mongo-b3bdf6ab-42ab-4d6a-8acf-a4f7cb940a1a.json, change/@apibara-plugin-sqlite-b026ca88-9927-4840-a95e-90776a18ccd0.json, change/apibara-9a822397-0994-4786-a9d7-0ad9986112d7.json, packages/cli/src/runtime/internal/app.ts, packages/indexer/build.config.ts, packages/indexer/package.json, packages/indexer/src/indexer.test.ts, packages/indexer/src/internal/index.ts, packages/indexer/src/internal/plugins.ts, packages/indexer/src/internal/testing.ts, packages/indexer/src/plugins/context.ts, packages/plugin-drizzle/src/index.ts, packages/plugin-drizzle/src/persistence.ts, packages/plugin-drizzle/src/storage.ts, packages/plugin-drizzle/src/utils.ts, packages/plugin-drizzle/tests/storage.test.ts, packages/plugin-mongo/src/index.ts, packages/plugin-mongo/src/persistence.ts, packages/plugin-mongo/tests/storage.test.ts, packages/plugin-sqlite/src/index.ts, packages/plugin-sqlite/src/persistence.ts, packages/plugin-sqlite/src/utils.ts, packages/plugin-sqlite/tests/kv.test.ts, packages/plugin-sqlite/tests/persistence.test.ts
Resolves #140 
- adds a `internalContext` plugin for runtime purpose
- adds a `generateIndexerId` util method
- fixes concurrency issue in creation of tables in parallel transactions in drizzle plugin
- updates test and plugins for the above
=> plugin-drizzle: fix concurrency issue during initialization

change/@apibara-indexer-7d0fe9aa-5dc3-4ba2-96c2-26a750edd3ec.json, change/apibara-613baa45-cb22-4333-9430-93f356634a9a.json, examples/cli/test/ethereum.test.ts, examples/cli/test/starknet.test.ts, examples/starknet-client/package.json, packages/cli/src/rollup/config.ts, packages/indexer/src/plugins/context.ts, packages/indexer/src/testing/index.ts, pnpm-lock.yaml
removes `esbuild` plugin from rollup config due to some issues with build, also adds missing `internalContext` plugin from `vcr` and updates tests for `cli` example.
=> cli: remove esbuild plugin from rollup config

change/@apibara-beaconchain-7b39a030-0724-44c0-8cec-7300e5efa49b.json, change/@apibara-evm-c96dd7a5-d16a-44aa-ac3a-947a9b904517.json, change/@apibara-plugin-drizzle-c4aaf5bc-24c6-4883-9b29-cf614279c5db.json, change/@apibara-plugin-mongo-ddb9c304-419b-4291-bb27-6c198e0501cd.json, change/@apibara-plugin-sqlite-ab552e08-0770-4528-b9a9-f1ffb9e0105f.json, change/@apibara-protocol-c3b43226-48fe-4e9f-abe7-760ca8e09b82.json, package.json, packages/beaconchain/package.json, packages/evm/package.json, packages/plugin-drizzle/package.json, packages/plugin-drizzle/src/persistence.ts, packages/plugin-drizzle/tests/storage.test.ts, packages/plugin-mongo/src/persistence.ts, packages/plugin-mongo/tests/storage.test.ts, packages/plugin-sqlite/package.json, packages/plugin-sqlite/src/persistence.ts, packages/protocol/src/common.ts
If the stored cursor has an empty uniqueKey, it's serialized as an empty string. This is an issue later when deserializing since that's not a valid value for the uniqueKey.
=> Fix deserialization issue with drizzle cursor

change/@apibara-indexer-b2bba30d-fe14-4236-830e-49c35d5e973a.json, change/apibara-f4a63aad-bcfe-435c-9522-12e7c8c95a4e.json, packages/cli/package.json, packages/cli/src/cli/commands/init.ts, packages/cli/src/create/add.ts, packages/cli/src/create/constants.ts, packages/cli/src/create/init.ts, packages/cli/src/create/templates.ts, packages/cli/src/create/utils.ts, packages/indexer/src/indexer.ts, pnpm-lock.yaml
adds file formatting with prettier, replaces `--no-create-indexer` flag to `--noIndexer` flag in `apibara init` and adds indexer file existence validation in prompt.
also adds validation for starting cursor in indexer.
=> cli: add file formatting with prettier and add noIndexer flag

change/apibara-267c95ee-bca5-40de-9b0f-348952969e0c.json, packages/cli/src/create/add.ts, packages/cli/src/create/init.ts
Hi,
When we init a new apibara project with `apibara init` the CLI invite us to run the command `npm run install` but is must be `npm install`.
In addition, I copied and pasted the whole command proposed by CLI without paying too much attention that I need to run install and prepare command separately, and an unexpected behaviour because of the `&`.
I suggest clarifying things a little by using the `&&` operator, thus allowing you to copy/paste the entire command, chaining the install and prepare commands. 
Regards
=> Fix wrong "install" command in CLI init command

change/@apibara-plugin-drizzle-a8baca91-31a7-4300-a577-67d13ce45e13.json, change/@apibara-plugin-mongo-88828ea1-dd82-428c-a257-048728e622d7.json, change/apibara-841ae10e-0109-447d-aa1a-95d763e33824.json, packages/cli/src/cli/commands/dev.ts, packages/plugin-drizzle/src/index.ts, packages/plugin-drizzle/src/persistence.ts, packages/plugin-drizzle/src/storage.ts, packages/plugin-mongo/src/index.ts, packages/plugin-mongo/src/mongo.ts, packages/plugin-mongo/src/persistence.ts, packages/plugin-mongo/src/utils.ts
adds a `--alwaysReindex` flag to `apibara dev` command which resets the database state on every restart of indexers.
=> feat: add --alwaysReindex flag in dev mode to reset database state on indexer restarts

change/@apibara-indexer-c30e94ee-538a-48f6-b0b1-66d2783ae188.json, change/@apibara-plugin-drizzle-5e0243be-f427-4e3b-b06e-f3e7bec2af3b.json, change/@apibara-plugin-mongo-5e9a70b3-021c-462d-9865-f886dc09b8ca.json, change/@apibara-plugin-sqlite-e6c5f565-8996-4a19-857e-54031f098166.json, packages/indexer/src/indexer.ts, packages/plugin-drizzle/src/index.ts, packages/plugin-drizzle/tests/helper.ts, packages/plugin-drizzle/tests/storage.test.ts, packages/plugin-mongo/src/index.ts, packages/plugin-mongo/tests/storage.test.ts, packages/plugin-sqlite/src/index.ts, packages/plugin-sqlite/src/kv.ts, packages/plugin-sqlite/src/persistence.ts, packages/plugin-sqlite/tests/kv.test.ts, packages/plugin-sqlite/tests/persistence.test.ts
adds logic to handle pending blocks in all three plugins - drizzle, mongo and sqlite.
adds a condition to not call factory function for pending blocks.
adds necessary tests for all plugins.
=> feat: handle pending blocks

.github/workflows/release.yml, change/@apibara-beaconchain-a2f3aecc-d68f-4565-abd5-54ad31d76e13.json, change/@apibara-evm-328b69a1-8d4e-47f7-b745-df6e9cfaa69a.json, change/@apibara-starknet-f65db5dd-f330-46e6-ad23-b5e9b8fb1939.json, packages/beaconchain/src/block.ts, packages/beaconchain/src/common.ts, packages/evm/src/block.ts, packages/evm/src/common.ts, packages/evm/src/filter.ts, packages/starknet/src/block.ts, packages/starknet/src/filter.ts
Some types were not exported but they are useful when implement indexers.
This PR exports all filter and block types.
=> Export missing network-specific types

.github/workflows/build.yml, .github/workflows/release.yml, change/@apibara-plugin-mongo-8a313e7a-5b45-4ae6-9727-2fa720b6f46c.json, examples/cli-drizzle/package.json, examples/cli-instrumentation/package.json, examples/cli-mongodb/apibara.config.mjs, examples/cli-mongodb/docker-compose.yaml, examples/cli-mongodb/indexers/starknet.indexer.js, examples/cli-mongodb/package.json, packages/plugin-mongo/src/persistence.ts, packages/plugin-mongo/src/utils.ts, pnpm-lock.yaml
The MongoDB had the following issues:
- calling `createCollection` on an already existing collection returns an error.
- `withTransaction` defaults to retrying by invoking the callback multiple times, but this is unacceptable for the middleware.
This PR fixes both issues.
=> plugin-mongo: fix errors on restart and retry

change/@apibara-plugin-drizzle-558402ff-418e-4c46-a661-863aafb32f4b.json, packages/plugin-drizzle/src/helper.ts
Apparently `postgresql://` is also valid.
=> Detect postgres connection string

change/@apibara-plugin-drizzle-fb22b1bc-f1ab-4299-a476-2ac25460956d.json, change/@apibara-plugin-mongo-c9018c01-2b4f-4a5a-a7a7-e13eb567d66f.json, change/@apibara-plugin-sqlite-22633833-27a0-4ae1-be3b-824b3514f5e2.json, change/apibara-34f7f808-dcf6-45ec-bbe4-5e74b0193361.json, examples/cli-drizzle/indexers/2-starknet.indexer.ts, examples/cli-drizzle/package.json, packages/cli/src/cli/commands/add.ts, packages/cli/src/cli/commands/build.ts, packages/cli/src/cli/commands/dev.ts, packages/cli/src/cli/commands/init.ts, packages/cli/src/cli/commands/prepare.ts, packages/cli/src/cli/commands/start.ts, packages/cli/src/cli/common.ts, packages/cli/src/create/constants.ts, packages/plugin-drizzle/src/index.ts, packages/plugin-drizzle/src/storage.ts, packages/plugin-drizzle/src/utils.ts, packages/plugin-mongo/src/index.ts, packages/plugin-sqlite/src/index.ts, packages/plugin-sqlite/src/kv.ts, packages/plugin-sqlite/src/persistence.ts, packages/plugin-sqlite/tests/kv.test.ts, pnpm-lock.yaml
- Fixes main process exiting on dev reloads
- Changes flag names on cli args
- Adds a validation for unknown args passed in cli, now throws error and prints help message.
- Bumps `drizzle-orm` version in template
- Fix cleanup query errors before initialization when `--always-reindex` flag is set
- Adds `indexerId` relation to KV Store
- Adds `idColumn` map support for table specific id column with wildcard support.
- Adds validation to check if all tables in schema has provided idColumns.
=> feat: qol improvements & fixes

change/@apibara-plugin-drizzle-f2a6ce16-c9f9-4f6a-8eb1-76dbfa580b88.json, change/apibara-9777cb0e-074c-4d75-a5c6-1730001d626c.json, packages/cli/src/cli/commands/dev.ts, packages/cli/src/create/templates.ts, packages/cli/src/runtime/dev.ts, packages/cli/src/runtime/internal/app.ts, packages/cli/src/runtime/start.ts, packages/plugin-drizzle/build.config.ts, packages/plugin-drizzle/package.json, packages/plugin-drizzle/src/helper.ts
- adds lazy imports to drizzle helpers
- improves `apibara dev` output
- makes postgres default db in `drizzle` helper
- updates cli templates to remove `postgresConnectionString` from `runtimeConfig`
=> feat: add lazy imports in drizzle helpers & improve dev output

change/@apibara-starknet-51bd3f88-6e7d-44b4-958e-febab812fe9a.json, packages/starknet/package.json, packages/starknet/src/abi-wan-helpers.ts, packages/starknet/src/event.ts, packages/starknet/src/index.ts, packages/starknet/src/parser.test-d.ts, packages/starknet/src/parser.ts, packages/starknet/tests/event.test-d.ts, packages/starknet/tests/event.test.ts, packages/starknet/tests/fixtures/ekubo-abi.ts, packages/starknet/tests/fixtures/golife-abi.ts, packages/starknet/tests/parser.test-d.ts
adds support for decoding enum events and respective tests, with added type-safety by extending `abi-wan-kanabi `
=> starknet: add enum event decoder

change/@apibara-plugin-drizzle-b88e8ea3-ca72-4abc-948b-166a319064e7.json, packages/plugin-drizzle/src/storage.ts
The issue is that timescale db works by "splitting" a table into many chunks. The value of `TG_TABLE_NAME` is not the name of the table, but the name of the chunk. So now we pass the table name to the function.
=> plugin-drizzle:  use table_name instead of TG_TABLE_NAME

change/@apibara-indexer-6840c283-48ae-4a3f-a3e7-706e002bd6a1.json, change/@apibara-protocol-aa5f0bd5-4da3-47e9-997b-32940c921233.json, packages/indexer/src/indexer.ts, packages/protocol/src/client.ts
Earlier, we had a reconnect logic for only `ClientError` instance, which wouldn't work for `ServerError`. So added a check for the same. Now indexer will reconnect on both `ClientError` and `ServerError` with status `INTERNAL`.
=> indexer: fix reconnect on internal server errors

change/apibara-72dcbda1-4e3a-4509-a2a0-3575ed36626f.json, packages/cli/src/core/apibara.ts, packages/cli/src/rolldown/config.ts
- this enables support for source-maps, so error traces can be more readable.
- also replaces `node-fetch` with `encoding` in `runtimeDependencies`, as running build file like `dev.mjs` directly with `node` would throw errors for `node-fetch`.
=> cli: adds support for source-maps

change/@apibara-beaconchain-adb65fa5-1af7-4e28-a28f-15ca24ee3129.json, change/@apibara-evm-4523fa2d-787a-451e-95fd-5a478163f971.json, change/@apibara-protocol-797f45f2-0d49-4e61-a606-13f653d35b9e.json, change/@apibara-starknet-ba02e3e3-1803-4976-8c82-f375e7d2eeba.json, change/apibara-9e98cb09-3f83-4b64-94b0-f5b58209961e.json, examples/cli-drizzle/apibara.config.ts, packages/beaconchain/src/index.ts, packages/cli/src/cli/commands/write-project-info.ts, packages/cli/src/cli/index.ts, packages/cli/src/core/build/prepare.ts, packages/cli/src/core/build/prod.ts, packages/cli/src/core/build/types.ts, packages/cli/src/runtime/project-info.ts, packages/cli/src/types/config.ts, packages/evm/src/index.ts, packages/protocol/src/config.ts, packages/protocol/src/testing/mock.ts, packages/starknet/src/index.ts
- updates `StreamConfig` class to accept chain name as argument, so all chain's name can be determined in runtime for metadata purpose from `Indexer` object. 
- adds a `write-project-info` command to cli, which creates `.apibara/project-info.json` with some metadata about indexers.
=> cli: add `write-project-info` command to generate `project-info.json`

change/apibara-935efd34-b737-4496-a67f-450a4f7caa7f.json, packages/cli/src/cli/commands/dev.ts
in `dev` mode, when there was an error in indexers, making changes would trigger reload but indexer wouldn't restart again, this fixes it.
=> cli: fix live reload when indexer errors

change/apibara-655744e6-c51d-4d42-aacc-99cc9f04026c.json, packages/cli/src/create/templates.ts
- removes `header: "always"` filter
- adds chain specific filters
- smol refactor
=> cli: update create template

change/@apibara-starknet-056a4593-d700-4325-aada-54b4af4cdd62.json, packages/starknet/package.json, packages/starknet/src/abi.ts, packages/starknet/src/event.ts, packages/starknet/src/parser.ts, packages/starknet/tests/event.test.ts, packages/starknet/tests/fixtures/payment-abi.ts, packages/starknet/tests/parser.test.ts, pnpm-lock.yaml
I changed the event decoder to parse byte arrays into bytes, represented as `0x${string}`.
=> Add byte array parser

change/@apibara-indexer-bbe8bf90-0f6e-40ea-a9c6-5d0546596537.json, change/@apibara-protocol-a12052ea-7467-4229-a1c0-ddfa00405c1d.json, change/apibara-727331a7-adfb-44e2-930e-200ff53ab011.json, examples/beaconchain-client/src/main.ts, examples/cli-drizzle/cassettes/ethereum-usdc-transfers.json, examples/cli-drizzle/cassettes/starknet-usdc-transfers.json, examples/evm-client/src/main.ts, examples/starknet-client/src/main.ts, packages/cli/src/runtime/dev.ts, packages/cli/src/runtime/internal/app.ts, packages/cli/src/runtime/start.ts, packages/indexer/src/testing/index.ts, packages/protocol/package.json, packages/protocol/src/client.ts, pnpm-lock.yaml
- moves `createAuthenticatedClient` from `cli` to `protocol` package
- use authenticated client in VCR
- updates all examples to use authenticated client
=> protocol: add createAuthenticatedClient
