apibara/typescript-sdk

.changeset/hip-paws-listen.md
examples/pending-data/package.json
examples/pending-data/src/main.ts
examples/pending-data/tsconfig.json
packages/protocol/src/proto/apibara/node/v1alpha1/StreamMessagesRequest.ts
packages/protocol/src/proto/apibara/node/v1alpha1/StreamMessagesResponse.ts
packages/protocol/src/proto/node.proto
turbo.json

Add support for pending data, with an example on how to use it.

Add pending data support

---

.changeset/thin-apricots-clean.md
.github/workflows/build.yml
examples/simple-client/src/main.ts
package.json
packages/protocol/jest.config.ts
packages/protocol/package.json
packages/protocol/src/client.ts
packages/protocol/src/stream.test.ts
packages/protocol/src/stream.ts
packages/protocol/tsconfig.json
packages/starknet/jest.config.ts
packages/starknet/package.json
packages/starknet/src/index.test.ts
packages/starknet/tsconfig.json
pnpm-lock.yaml
turbo.json

- protocol: reconnect stream on disconnect
- ci: test packages

Add option to reconnect stream

---

.changeset/curvy-ladybugs-explode.md
.changeset/modern-dolphins-begin.md
.changeset/pre.json
examples/simple-client/src/main.ts

Release next version, with support for the protocol v1alpha2

Release next version

---

.changeset/gold-tigers-ring.md
.changeset/proud-clocks-live.md
examples/simple-client/src/main.ts
packages/protocol/src/client.ts
packages/starknet/src/filter.ts
packages/starknet/src/proto/filter.proto
packages/starknet/src/proto/generated.d.ts
packages/starknet/src/proto/generated.js

- protocol: rethrow error if not reconnecting
- starknet: include weak header flag

Add support for weak header

---

.changeset/yellow-spies-hammer.md
.editorconfig
packages/protocol/src/client.ts

This change improves detecting if the connection between the server and
client hang.

protocol: add timeout while waiting for messages

---

.changeset/spotty-pianos-give.md
packages/indexer/README.md
packages/indexer/package.json
packages/indexer/src/config.ts
packages/indexer/src/index.ts
packages/indexer/src/sink/console.ts
packages/indexer/src/sink/mongo.ts
packages/indexer/src/sink/parquet.ts
packages/indexer/src/sink/postgres.ts
packages/indexer/src/sink/webhook.ts
packages/indexer/src/starknet/block.ts
packages/indexer/src/starknet/filter.ts
packages/indexer/src/starknet/index.ts
packages/indexer/tsconfig.json
pnpm-lock.yaml
turbo.json

This package will be used in indexer scripts.

Create indexer package with type definitions and helpers

---

packages/indexer/package.json
packages/indexer/src/starknet/parser.test.ts
packages/indexer/src/starknet/parser.ts
pnpm-lock.yaml

- Created `parser.ts` file inside the `packages/indexer` directory
- WIP on the `eventFilter` and `eventParser` method.
Issue: https://github.com/apibara/typescript-sdk/issues/54

feat: wip on parser

---

.changeset/beige-singers-smile.md
biome.json
examples/starknet-client/index.ts
examples/starknet-client/package.json
packages/protocol/src/client.ts
packages/protocol/src/proto/apibara/node/v1alpha2/Data.ts
packages/protocol/src/proto/apibara/node/v1alpha2/DataFinality.ts
packages/protocol/src/proto/apibara/node/v1alpha2/StreamDataRequest.ts
packages/protocol/src/request.test.ts
pnpm-lock.yaml
tsconfig.json

protocol: fix stream client to yield heartbeat messages
Add examples

protocol: fix stream client to yield heartbeat messages

---

.changeset/friendly-months-grow.md
.changeset/gentle-rules-hide.md
packages/indexer/src/starknet/block.test-d.ts
packages/indexer/src/starknet/block.ts
packages/starknet/src/proto/generated.d.ts
packages/starknet/src/proto/generated.js
packages/starknet/src/proto/starknet.proto

starknet: add V3 transactions
indexer: add v3 transaction types

starknet: add V3 transactions

---

.changeset/beige-tables-relate.md
.changeset/sour-pugs-type.md
.github/workflows/build.yml
flake.lock
flake.nix
package.json
packages/indexer/package.json
packages/indexer/src/config.test-d.ts
packages/indexer/src/sink/console.test-d.ts
packages/indexer/src/starknet/block.test-d.ts
packages/indexer/src/starknet/block.ts
packages/indexer/src/starknet/filter.test-d.ts
packages/indexer/src/starknet/filter.ts
packages/indexer/src/starknet/index.ts
packages/indexer/src/starknet/parser.test.ts
packages/indexer/src/starknet/parser.ts
packages/protocol/jest.config.ts
packages/protocol/package.json
packages/protocol/src/client.ts
packages/protocol/src/cursor.ts
packages/protocol/src/request.ts
packages/starknet/jest.config.ts
packages/starknet/package.json
packages/starknet/src/cursor.ts
packages/starknet/src/filter.ts
packages/starknet/src/proto/generated.d.ts
packages/starknet/src/proto/generated.js
packages/starknet/src/proto/index.ts
packages/starknet/src/proto/starknet.proto
pnpm-lock.yaml

- Update nix flake and nodejs version
- starknet: update type definitions for Starknet v0.13.1 and RPC 0.7.1
- indexer: update starknet type definitions

Update starknet type definitions

---

examples/indexer/package.json
examples/indexer/src/indexer.ts
packages/indexer/package.json
packages/indexer/src/index.ts
packages/indexer/src/indexer.ts
packages/indexer/src/sink.ts
packages/indexer/src/sinks/index.ts
packages/indexer/src/sinks/sqlite.ts
pnpm-lock.yaml
tsconfig.json

feat: SQLite Sink

---

packages/evm/src/block.ts
packages/evm/src/common.test.ts
packages/evm/src/common.ts

added missing evm data definitions and schemas.

feat: added evm data definitions

---

examples/indexer/package.json
packages/indexer/package.json
packages/indexer/src/sinks/csv.ts
packages/indexer/src/sinks/sqlite.ts
pnpm-lock.yaml

feat: CsvSink

---

packages/evm/src/block.ts
packages/indexer/package.json
packages/indexer/src/index.ts
packages/indexer/src/indexer.ts
packages/indexer/src/vcr/client.ts
packages/indexer/src/vcr/config.ts
packages/indexer/src/vcr/helper.ts
packages/indexer/src/vcr/index.ts
packages/indexer/src/vcr/record.ts
packages/indexer/src/vcr/replay.ts
packages/protocol/src/client.ts
pnpm-lock.yaml

Add VCR streaming which can record streams to a file and replay them without connecting to the actual stream.

Add VCR streaming 

---

.github/workflows/build.yml
examples/evm-client/package.json
examples/indexer/package.json
examples/starknet-client/package.json
package.json
packages/evm/package.json
packages/indexer/package.json
packages/protocol/package.json
packages/starknet/package.json
turbo.json

Add a typecheck command to test types before building

Add typecheck command

---

.github/workflows/build.yml
.github/workflows/release.yml
examples/indexer/src/indexer.ts
package.json
packages/beaconchain/package.json
packages/evm/package.json
packages/indexer/package.json
packages/indexer/src/indexer.test.ts
packages/indexer/src/indexer.ts
packages/indexer/src/plugins/persistence.test.ts
packages/indexer/src/plugins/persistence.ts
packages/indexer/src/testing/helper.ts
packages/indexer/src/testing/indexer.ts
packages/indexer/src/vcr/replay.ts
packages/protocol/package.json
packages/protocol/src/proto/index.ts
packages/protocol/src/stream.ts
packages/protocol/src/testing/client.test.ts
packages/protocol/src/testing/client.ts
packages/starknet/package.json
turbo.json

add factory mode and tests.
update persistence plugin to store filters and update tests.

indexer: add factory mode

---

examples/indexer/package.json
packages/indexer/package.json
packages/indexer/src/indexer.test.ts
packages/indexer/src/plugins/kv.test.ts
packages/indexer/src/plugins/kv.ts
packages/indexer/src/plugins/persistence.test.ts
packages/indexer/src/plugins/persistence.ts
packages/indexer/src/sinks/csv.test.ts
packages/indexer/src/sinks/csv.ts
packages/indexer/src/sinks/sqlite.test.ts
packages/indexer/src/sinks/sqlite.ts
pnpm-lock.yaml

- remove sqlite & sqlite3 and replace it with better-sqlite3
- add test for csv and sqlite sink

indexer: add better-sqlite3

---

change/@apibara-beaconchain-e098927f-8fca-4424-8a04-c4f606e0b814.json
change/@apibara-evm-341a2ca1-f567-42d7-a1a9-e90ecfd9d543.json
change/@apibara-indexer-113c7adb-5476-49e2-94a0-5287db28bbde.json
change/@apibara-plugin-drizzle-6319c857-e665-48da-bb38-5b6d735a501b.json
change/@apibara-plugin-mongo-70ea377f-490f-434b-b7e4-3d65e9a0844d.json
change/@apibara-plugin-sqlite-2879a78b-9553-4240-aa1c-79cee697301f.json
change/@apibara-protocol-c98c44d8-53fd-4af0-8689-04cada9f961d.json
change/@apibara-starknet-572bf2f8-a9b7-41e2-8df1-0bff1ce38aaf.json
change/apibara-884dabca-c512-4586-a7a7-98eb268fb9a4.json
examples/beaconchain-client/package.json
examples/cli-js/package.json
examples/cli/package.json
examples/evm-client/package.json
examples/starknet-client/package.json
packages/beaconchain/package.json
packages/cli/package.json
packages/cli/src/create/constants.ts
packages/evm/package.json
packages/indexer/package.json
packages/plugin-drizzle/package.json
packages/plugin-mongo/package.json
packages/plugin-sqlite/package.json
packages/protocol/package.json
packages/starknet/package.json

Let's re-align packages' version.

Update beta to 2.1.0-beta.x

---

change/apibara-407b14c0-e0c4-4247-82f6-0ed6542f6e01.json
packages/cli/package.json
packages/cli/src/core/build/error.ts
packages/cli/src/core/config/defaults.ts
packages/cli/src/rollup/config.ts
packages/cli/src/rollup/plugins/indexers.ts
packages/cli/src/runtime/dev.ts
packages/cli/src/runtime/internal/app.ts
packages/cli/src/runtime/start.ts
packages/cli/src/types/config.ts
packages/cli/src/types/virtual/indexers.d.ts
pnpm-lock.yaml

This PR fixes a build issue if an indexer has no exports.
Now it prints a warning in development mode and an error in production mode.

Fix build if indexer has no exports

---

change/@apibara-plugin-drizzle-7e14dc88-22db-431b-9354-00dcebeffd70.json
packages/plugin-drizzle/package.json
pnpm-lock.yaml

This PR relaxes the version of drizzle and pg

Relax drizzle peer version

---

change/@apibara-evm-6058fbe6-0253-418c-88b3-63d694956316.json
change/@apibara-starknet-c13decf4-028c-474f-8fd1-a0277c5591ed.json
examples/evm-client/src/main.ts
examples/starknet-client/src/main.ts
packages/evm/proto/data.proto
packages/evm/proto/filter.proto
packages/evm/src/block.ts
packages/evm/src/filter.ts
packages/evm/src/helpers.ts
packages/evm/src/proto/data.ts
packages/evm/src/proto/filter.ts
packages/starknet/proto/data.proto
packages/starknet/proto/filter.proto
packages/starknet/src/block.ts
packages/starknet/src/filter.ts
packages/starknet/src/proto/data.ts
packages/starknet/src/proto/filter.ts

This PR adds support for traces for customers that enabled them in their dedicated DNA nodes.

Add trace definitions

---

change/@apibara-evm-020d0fba-1d28-4896-bfb8-dc0f93f4bc2e.json
examples/evm-client/src/main.ts
packages/evm/proto/data.proto
packages/evm/src/block.ts
packages/evm/src/proto/data.ts

This new field started appearing on Sepolia today.

evm: add requests hash header

---

change/@apibara-indexer-ea4f1aaf-4717-4f28-b73f-7c8dae6984b5.json
change/apibara-f2008045-735b-46bb-bc59-e3b2d04aad0c.json
examples/cli-drizzle/indexers/1-evm.indexer.ts
examples/cli-drizzle/indexers/2-starknet.indexer.ts
examples/cli-drizzle/indexers/3-starknet-factory.indexer.ts
examples/cli-instrumentation/indexers/starknet.indexer.ts
examples/cli-js/indexers/evm.indexer.js
examples/cli-js/indexers/starknet.indexer.js
examples/cli-js/package.json
examples/cli-mongodb/indexers/starknet.indexer.js
examples/evm-client/src/main.ts
examples/starknet-client/src/main.ts
packages/cli/src/create/constants.ts
packages/indexer/src/indexer.ts
pnpm-lock.yaml

Some users use this field to implement code that is only run when reaching the chain's tip.

Add block production field to handler args
